name: flutter_iem_new
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  web_socket_channel: ^3.0.1
  stomp_dart_client: ^2.1.1
  flutter_keyboard_visibility: 6.0.0
  flutter_dotenv: ^5.0.2
  regexed_validator: ^2.0.0+1
  flutter_thermal_printer: ^1.0.1
  flutter_ringtone_player: ^4.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.production
    - .env.development
